'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    welcomeBack: 'Welcome Back',
    loginSubtitle: 'Login to continue optimizing your career',
    emailAddress: 'Email Address',
    enterEmail: 'Enter your email',
    password: 'Password',
    enterPassword: 'Enter your password',
    rememberMe: 'Remember me',
    forgotPassword: 'Forgot password?',
    login: 'Login',
    orContinueWith: 'Or continue with',
    continueWithGoogle: 'Continue with Google',
    orSignUpWith: 'Or sign up using',
    continueWithGoogleSignUp: 'Continue with Google',
    noAccount: "Don't have an account?",
    signUp: 'Sign Up',
    createAccount: 'Create account',
    signupSubtitle: 'Create an account to continue optimizing your career',
    fullName: 'Full Name',
    enterFullName: 'Enter your full name',
    networkStrength: 'Network strength',
    confirmPassword: 'Confirm Password',
    reEnterPassword: 'Re-enter your password',
    agreeToTerms: 'I agree to the Terms of Service and Privacy Policy',
    createAccountBtn: 'Create Account',
    haveAccount: 'Already have an account?',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    signInSuccess: 'Welcome back! You have signed in successfully.',
    signUpSuccess: 'Account created successfully! Please check your email.',
    failedToSignIn: 'Failed to sign in. Please check your credentials.',
    signOut: 'Sign Out',
    signingOut: 'Signing out...',
    signOutSuccess: 'You have been signed out successfully.',
    signOutError: 'Failed to sign out. Please try again.',
    signOutConfirmTitle: 'Sign Out',
    signOutConfirmMessage: 'Are you sure you want to sign out of your account?',
    cancel: 'Cancel',
    // Auth Success/Error Messages
    accountCreated: 'Account Created!',
    emailVerified: 'Email verified successfully! You are now logged in.',
    emailVerifiedTitle: "You're In!",
    emailVerifiedMessage: "Your email has been verified. Welcome to ResumeAI!",
    verificationEmailSent: 'We have sent a verification email to:',
    checkEmailToVerify: 'Please check your email and click the verification link to activate your account.',
    emailResentSuccess: 'Verification email has been resent!',
    resendEmail: 'Resend Verification Email',
    resendIn: 'Resend in',
    sending: 'Sending...',
    goToSignIn: 'Go to Sign In',
    creatingAccount: 'Creating account...',
    passwordsDoNotMatch: 'Passwords do not match.',
    passwordTooShort: 'Password must be at least 6 characters long.',
    mustAgreeToTerms: 'You must agree to the terms and conditions.',
    failedToCreateAccount: 'Failed to create account. Please try again.',
    accountCreatedSignInFailed: 'Account created but sign in failed. Please try signing in manually.',
    failedToResendEmail: 'Failed to resend email. Please try again.',
    failedGoogleSignUp: 'Failed to sign up with Google.',
    unexpectedError: 'An unexpected error occurred. Please try again.',
    verificationFailed: 'Email verification failed. Please try again or request a new verification email.',
    authFailed: 'Authentication failed. Please try again.',
    // Friendly signin error messages
    wrongPassword: "That password doesn't look right. Give it another try!",
    pleaseVerifyFirst: 'Please verify your email first. Check your inbox!',
    noAccountFound: "We couldn't find an account with that email. Let's create one!",
    tooManyTries: 'Too many attempts. Take a breather and try again in a bit.',
    somethingWentWrong: 'Something went wrong. Please try again.',
    oopsSomethingWrong: 'Oops! Something went wrong. Please try again.',
    invalidCredentials: 'Incorrect email or password.',
    letsGetYouStarted: "Let's get you started! Just fill in the details below.",
    signUpRequired: 'Sign Up Required',
    signUpToUpload: 'Please create an account or sign in to upload your resume and use CVLab\'s AI-powered optimization.',
    signUpNow: 'Sign Up Now',
    optimizeCV: 'Optimize Your CV with CVLab',
    optimizeCareer: 'Optimize Your Career with CVLab',
    transformResume: 'Transform your resume with intelligent optimization and land your dream job with easier',
    transformCV: 'Transform your resume with CVLab and land your dream job faster than ever.',
    weak: 'Weak',
    good: 'Good',
    strong: 'Strong',
    home: 'Home',
    about: 'About Us',
    contact: 'Contact Us',
    getStarted: 'Get Started',
    heroTitle: 'Your Resume, Perfected by CVLab',
    heroSubtitle: 'Upload your CV and let AI analyze, enhance, and optimize it for top-tier job applications in seconds.',
    dropResume: 'Drop your resume here',
    supportedFormats: 'Supports PDF, DOCX + Max 10MB',
    uploadResume: 'Upload Resume',
    howItWorks: 'How It Works',
    stepSubtitle: 'Three simple steps to a perfect resume',
    step1Title: 'Upload Your Resume',
    step1Desc: 'Simply drag and drop your resume or click to upload. We support all major formats.',
    step2Title: 'AI Analyzes & Improves',
    step2Desc: 'Our AI scans your resume for improvements in grammar, keywords, and formatting.',
    step3Title: 'Download Optimized Version',
    step3Desc: 'Get your professionally optimized resume ready to impress recruiters.',
    resumeAI: 'ResumeAI',
    perfectingResumes: 'Perfecting resumes with CVLab',
    quickLinks: 'Quick Links',
    legal: 'Legal',
    privacyPolicy: 'Privacy Policy',
    termsOfService: 'Terms of Service',
    // Terms of Service Page
    termsTitle: 'Terms & Conditions',
    termsSubtitle: 'CVLab سيفي لاب',
    termsLastUpdated: 'Last Updated: January 2026',
    termsSection1Title: '1. Introduction',
    termsSection1Text: 'Welcome to CVLab ("we," "our," or "us"). By accessing or using our website and services, you agree to be bound by these Terms and Conditions. Please read them carefully before using our CV creation platform.',
    termsSection2Title: '2. Definitions',
    termsSection2Text: '"Service" refers to the CV/resume creation tools, templates, and related features provided by CVLab.\n\n"User" refers to any individual who accesses or uses our Service.\n\n"Content" refers to any text, images, data, or materials uploaded, created, or generated through our Service.',
    termsSection3Title: '3. Account Registration',
    termsSection3Text: 'To access certain features, you may need to create an account. You agree to provide accurate and complete information during registration and to keep your account credentials secure. You are responsible for all activities that occur under your account.',
    termsSection4Title: '4. Services Description',
    termsSection4Text: 'CVLab provides online tools for creating, editing, and downloading professional CVs and resumes. We offer various templates, formatting options, and export capabilities. Features may vary based on subscription plans.',
    termsSection5Title: '5. User Responsibilities',
    termsSection5Text: 'You agree to use our Service only for lawful purposes and in accordance with these Terms. You shall not use the Service to create false, misleading, or fraudulent documents. You are solely responsible for the accuracy of information included in your CV.',
    termsSection6Title: '6. Intellectual Property',
    termsSection6Text: 'All templates, designs, software, and other materials provided by CVLab are protected by intellectual property rights. You may use these materials solely for personal, non-commercial purposes. You retain ownership of your personal content and data.',
    termsSection7Title: '7. Purchases and Payment',
    termsSection7Text: 'Certain features may require payment. All prices are displayed in the applicable currency and include any applicable taxes unless stated otherwise. Payment must be made through our approved payment methods. By making a purchase, you authorize us to charge your selected payment method.',
    termsSection8Title: '8. Refunds and Returns Policy',
    termsSection8Text: 'Due to the digital nature of our services, refunds are generally not available once a service has been accessed or downloaded. However, we may consider refund requests on a case-by-case basis within 14 days of purchase if the service was not delivered as described or technical issues prevented access. To request a refund, please contact our support team with your order details.',
    termsSection9Title: '9. Privacy',
    termsSection9Text: 'Your use of our Service is also governed by our Privacy Policy. We collect and process personal data as described therein. By using our Service, you consent to such processing.',
    termsSection10Title: '10. Limitation of Liability',
    termsSection10Text: 'To the maximum extent permitted by law, CVLab shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service. Our total liability shall not exceed the amount paid by you for the Service.',
    termsSection11Title: '11. Changes to Terms',
    termsSection11Text: 'We reserve the right to modify these Terms at any time. Changes will be effective upon posting. Your continued use of the Service after changes constitutes acceptance of the modified Terms.',
    termsSection12Title: '12. Governing Law',
    termsSection12Text: 'These Terms shall be governed by and construed in accordance with the applicable laws of the jurisdiction in which CVLab operates.',
    termsSection13Title: '13. Contact Us',
    termsSection13Text: 'If you have any questions about these Terms, please contact us through our website.',
    copyright: '© 2026 CVLab. All rights reserved.',
    // About Us Page
    aboutUsTitle: 'About Us',
    aboutUsSubtitle: 'CVLab سيفي لاب',
    aboutUsWhoWeAreTitle: 'Who We Are',
    aboutUsWhoWeAreText: 'CVLab is an intelligent CV enhancement platform designed to help you create a professional, polished resume that truly represents your skills and experience.',
    aboutUsHowItWorksTitle: 'How It Works',
    aboutUsHowItWorksSubtitle: 'Our platform uses a simple yet powerful approach:',
    aboutUsStep1Title: 'Upload Your CV',
    aboutUsStep1Desc: 'Submit your existing CV to our platform.',
    aboutUsStep2Title: 'Smart Review',
    aboutUsStep2Desc: 'We analyze your CV and identify areas that need clarification or improvement.',
    aboutUsStep3Title: 'Interactive Questions',
    aboutUsStep3Desc: 'We ask you targeted questions about unclear or incomplete sections.',
    aboutUsStep4Title: 'Professional Rewrite',
    aboutUsStep4Desc: 'Based on your answers, we rewrite your CV into a polished, professional document.',
    aboutUsMissionTitle: 'Our Mission',
    aboutUsMissionText: 'We believe everyone deserves a CV that opens doors. Our goal is to bridge the gap between your potential and your presentation, helping you stand out to employers.',
    // Processing Page
    processingTitle: 'Finalizing your enhanced resume...',
    processingDescription: 'Applying final touches and preparing your optimized resume with detailed recommendations and insights.',
    processingStatusLabel: 'AI Optimization in Progress',
    processingLabel: 'Processing',
    proTipTitle: 'Pro Tip',
    proTipText: 'Well-optimized resumes can increase interview chances by up to 70%.',
    // Payment Page
    paymentTitle: 'Complete Your Payment',
    paymentDescription: 'Your resume is ready for AI optimization. Complete payment to unlock professional analysis and improvements.',
    secureCheckout: 'Secure Checkout',
    orderSummary: 'Order Summary',
    aiWillOptimize: 'AI will optimize:',
    atsOptimization: 'ATS Optimization',
    grammarClarity: 'Grammar & Clarity Fix',
    keywordEnhancement: 'Keyword Enhancement',
    professionalFormatting: 'Professional Formatting',
    resumeOptimization: 'Resume Optimization',
    total: 'Total',
    paymentDetails: 'Payment Details',
    limitedOffer: 'Limited Time: 50% OFF',
    contactInformation: 'Contact Information',
    emailAddressLabel: 'Email Address',
    paymentMethod: 'Payment Method',
    card: 'Card',
    cardNumber: 'Card Number',
    expiryDate: 'Expiry Date',
    cvc: 'CVC',
    saveCard: 'Save card for future purchases',
    payOptimize: 'Pay & Optimize My Resume',
    securePayment: 'Secure payment powered by Stripe',
    noRecurring: 'No recurring charges — one-time payment only',
    readyForOptimization: 'Your resume is ready for AI optimization. Complete the payment to continue and receive your professionally optimized resume within minutes.',
    // Profile Page
    profile: 'Profile',
    'profile.title': 'Profile',
    'profile.subtitle': 'Manage your personal account information',
    'profile.changePhoto': 'Change Photo',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.email': 'Email Address',
    'profile.changePassword': 'Change Password',
    'profile.currentPassword': 'Current Password',
    'profile.newPassword': 'New Password',
    'profile.confirmPassword': 'Confirm New Password',
    'profile.saveChanges': 'Save Changes',
    'profile.cancel': 'Cancel',
    'profile.accountActions': 'Account Actions',
    'profile.downloadData': 'Download Data',
    'profile.logout': 'Logout',
    'profile.deleteAccount': 'Delete Account',
    'profile.accountInfo': 'Account Info',
    'profile.memberSince': 'Member since',
    'profile.lastSignIn': 'Last Sign In',
    'profile.january2023': 'Jan 2023',
    'profile.twoDaysAgo': '2 days ago',
    'profile.lastUpdated': 'Last updated',
    'profile.activityHistory': 'Activity History',
    'profile.noActivity': 'No Activity',
    'profile.uploadResumeToSeeActivity': 'Upload a resume to see your activity history',
    'profile.resumeDownloaded': 'Resume downloaded',
    'profile.downloadedOptimized': 'Downloaded optimized version in PDF format',
    'profile.daysAgo': 'days ago',
    'profile.twoDaysAgoActivity': '2 days ago',
    // Contact Page
    'contact.title': 'Contact Us',
    'contact.subtitle': "We're here to help. Reach out anytime.",
    'contact.contactInfo': 'Contact Information',
    'contact.email': 'Email',
    'contact.address': 'Address',
    'contact.riyadh': 'Riyadh',
    'contact.saudiArabia': 'Saudi Arabia',
    'contact.addressFull': 'Riyadh, Saudi Arabia',
    'contact.faq': 'Frequently Asked Questions',
    'contact.faq1': 'How does resume optimization work?',
    'contact.faq2': 'Is my data safe and secure?',
    'contact.faq3': 'How long does optimization take?',
    'contact.sendMessage': 'Send Us a Message',
    'contact.replyTime': 'We usually reply within 24 hours',
    'contact.fullName': 'Full Name',
    'contact.fullNamePlaceholder': 'Enter your full name',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phoneNumber': 'Phone Number',
    'contact.phonePlaceholder': '05########',
    'contact.message': 'Message',
    'contact.messagePlaceholder': 'Write your message here...',
    'contact.sendBtn': 'Send Message',
    'contact.confidential': 'Your information is confidential and secure',
    'contact.needHelp': 'Need Immediate Help?',
    'contact.supportText': 'Our support team is available to assist you anytime. We value your time and strive to resolve your inquiries as quickly as possible.',
    'contact.liveChat': 'Live Chat',
    'contact.helpCenter': 'Help Center',
    // Questions Page
    questions: 'Questions',
    ready: 'Ready',
    pages: 'pages',
    resumeOptimizationTitle: 'Resume Optimization Questions',
    resumeOptimizationSubtitle: 'Answer the following questions to help us personalize your resume analysis and provide the most relevant recommendations',
    progress: 'Progress',
    question1Title: 'What is your target job title?',
    question1Subtitle: 'This helps us tailor recommendations for your specific career goals',
    question1Placeholder: 'e.g., Senior Software Engineer, Marketing Manager',
    question2Title: 'What industry are you targeting?',
    question2Subtitle: 'Different industries have different keyword preferences',
    question2Placeholder: 'e.g., Technology, Healthcare, Finance, Marketing',
    question3Title: 'Years of experience?',
    question3Subtitle: 'This helps us calibrate the analysis for your career level',
    question3Placeholder: 'e.g., 0-2 years, 3-5 years, 5-10 years, 10+ years',
    question4Title: 'What are your key skills?',
    question4Subtitle: 'List your top 5-10 skills that are most relevant to your target role',
    question4Placeholder: 'e.g., Python, Project Management, Data Analysis, Leadership, React...',
    question5Title: 'Do you have a specific job posting in mind?',
    question5Subtitle: 'Optional: Paste the job description URL or key requirements to optimize for that specific role',
    question5Placeholder: 'Paste job description URL or key requirements here (Optional)',
    analyzeButton: 'Analyze & Optimize Resume',
    // Resume Preview Page
    'templateSelector.title': 'Select CV Template',
    'templateSelector.classic.name': 'Classic',
    'templateSelector.classic.description': 'Traditional & Professional',
    'templateSelector.classic.tag1': 'ATS Friendly',
    'templateSelector.classic.tag2': 'Clean Layout',
    'templateSelector.modern.name': 'Modern',
    'templateSelector.modern.description': 'Contemporary & Creative',
    'templateSelector.modern.tag1': 'Bold Design',
    'templateSelector.modern.tag2': 'Eye-catching',
    'templateSelector.executive.name': 'Executive',
    'templateSelector.executive.description': 'Leadership & Senior Roles',
    'templateSelector.executive.tag1': 'Elegant',
    'templateSelector.executive.tag2': 'Sophisticated',
    'templateSelector.technical.name': 'Technical',
    'templateSelector.technical.description': 'IT & Engineering Roles',
    'templateSelector.technical.tag1': 'Skills Focus',
    'templateSelector.technical.tag2': 'Tech Stack',
    'optimization.title': 'Optimization Tips',
    'optimization.atsOptimized': 'Your resume has been optimized for ATS systems',
    'optimization.keywordsEnhanced': 'Keywords have been enhanced by 35%',
    'optimization.formattingImproved': 'Formatting improved for readability',
    'resumePreview.title': 'Resume Preview',
    'resumePreview.download': 'Download CV on PDF & Word',
    'resume.professionalSummary': 'Professional Summary',
    'resume.workExperience': 'Work Experience',
    'resume.education': 'Education',
    'resume.technicalSkills': 'Technical Skills',
    'resume.certifications': 'Certifications',
    'resume.present': 'Present',
    'resume.name': 'Abdullah Alshehri',
    'resume.title': 'Senior Software Engineer',
    'resume.email': 'abdullah@email.com',
    'resume.phone': '+966 50 123 4567',
    'resume.location': 'Riyadh, Saudi Arabia',
    'resume.professionalSummaryText': 'Results-driven Senior Software Engineer with 8+ years of experience in full-stack development, cloud architecture, and team leadership. Proven track record of delivering scalable solutions that improve system performance by 40% and reduce operational costs by $200K annually.',
    'resume.workExp1.title': 'Senior Software Engineer',
    'resume.workExp1.company': 'Tech Solutions Inc.',
    'resume.workExp1.period': '2020 - Present',
    'resume.workExp1.bullet1': 'Led a team of 6 engineers to develop microservices architecture, improving system scalability by 60%',
    'resume.workExp1.bullet2': 'Implemented CI/CD pipelines reducing deployment time from 4 hours to 15 minutes',
    'resume.workExp1.bullet3': 'Optimized database queries resulting in 45% faster response times',
    'resume.workExp2.title': 'Software Engineer',
    'resume.workExp2.company': 'Digital Innovations LLC',
    'resume.workExp2.period': '2017 - 2020',
    'resume.workExp2.bullet1': 'Developed RESTful APIs serving 1M+ daily requests with 99.9% uptime',
    'resume.workExp2.bullet2': 'Collaborated with cross-functional teams to deliver 15+ projects on time',
    'resume.education.degree': 'Bachelor of Computer Science',
    'resume.education.university': 'King Saud University',
    'resume.education.period': '2013 - 2017',
    'resume.skills.languages': 'Languages',
    'resume.skills.languagesList': 'Python, JavaScript, Java, Go',
    'resume.skills.frameworks': 'Frameworks',
    'resume.skills.frameworksList': 'React, Node.js, Django',
    'resume.skills.cloud': 'Cloud',
    'resume.skills.cloudList': 'AWS, Azure, Docker, Kubernetes',
    'resume.skills.databases': 'Databases',
    'resume.skills.databasesList': 'PostgreSQL, MongoDB, Redis',
    'resume.cert1': 'AWS Certified Solutions Architect',
    'resume.cert2': 'Certified Kubernetes Administrator',
    'resume.cert3': 'Professional Scrum Master I',
    // Prompt Management Page (/prompt-management)
    'pm.brand': 'AdminHub',
    'pm.nav.admin': 'Admin',
    'pm.nav.dashboard': 'Dashboard',
    'pm.user.adminUser': 'Admin User',
    'pm.user.email': 'admin@company.com',
    'pm.page.title': 'Prompt Management',
    'pm.page.subtitle':
      'Configure AI models and manage prompt templates for resume analysis',
    'pm.llm.title': 'LLM Configuration',
    'pm.llm.provider': 'LLM Provider',
    'pm.llm.model': 'Model',
    'pm.llm.saveButton': 'Save Model Configuration',
    'pm.prompt.analyzeResume.title': 'Analyze Resume Prompt',
    'pm.prompt.analyzeResume.subtitle':
      'Template for comprehensive resume analysis',
    'pm.prompt.analyzeResume.description':
      'Perform a comprehensive analysis of the provided resume. Evaluate the following aspects: 1. Overall structure and formatting quality 2. Content relevance and completeness 3. Skills alignment with industry standards 4. Experience presentation and quantification 5. ATS compatibility and keyword optimization Provide a detailed score (1-10) for each category with explanations and improvement recommendations.',
    'pm.prompt.analyzeResume.lastUpdated': '5 hours ago',
    'pm.prompt.questionGeneration.title': 'Question Generation Prompt',
    'pm.prompt.questionGeneration.subtitle':
      'Template for generating interview questions based on resume',
    'pm.prompt.questionGeneration.description':
      "Based on the provided resume, generate relevant interview questions that would help assess the candidate's qualifications. Create questions in the following categories: 1. Technical skills and expertise 2. Experience-based behavioral questions 3. Achievement and accomplishment inquiries 4. Problem-solving scenario questions 5. Culture fit and motivation questions Provide 3-5 questions per category with varying difficulty levels.",
    'pm.prompt.questionGeneration.lastUpdated': '1 day ago',
    'pm.prompt.optimizeResume.title': 'Optimize Resume Prompt',
    'pm.prompt.optimizeResume.subtitle':
      'Template for resume optimization suggestions',
    'pm.prompt.optimizeResume.description':
      'You are an expert resume optimizer. Analyze the provided resume and suggest specific improvements to enhance its effectiveness for job applications. Focus on: 1. Content optimization and keyword enhancement 2. Format and structure improvements 3. Skills highlighting and quantification 4. Achievement-based language recommendations Provide actionable feedback with specific examples.',
    'pm.prompt.optimizeResume.lastUpdated': '2 hours ago',
    'pm.buttons.preview': 'Preview',
    'pm.buttons.edit': 'Edit',
    'pm.buttons.saveChanges': 'Save Changes',
    'pm.lastUpdated': 'Last updated:',
    'pm.status.active': 'Active',
    'pm.status.draft': 'Draft',
    // Admin (cv-build /admin/*)
    'admin.adminHub': 'AdminHub',
    'admin.admin': 'Admin',
    'admin.overview': 'Overview',
    'admin.dashboardOverview': 'Overview',
    'admin.monitorPerformance': 'Monitor system performance and user activity',
    'admin.dashboard': 'Dashboard',
    'admin.prompts': 'Prompts',
    'admin.resumes': 'Resumes',
    'admin.users': 'Users',
    'admin.claims': 'Claims',
    'admin.settings': 'Settings',
    'admin.totalUsers': 'Total Users',
    'admin.totalSessions': 'Total Sessions',
    'admin.resumesProcessed': 'Resumes Processed',
    'admin.serverUptime': 'Server Uptime',
    'admin.userManagement': 'User Management',
    'admin.searchUsers': 'Search users...',
    'admin.allStatus': 'All Status',
    'admin.allRoles': 'All Roles',
    'admin.roleUser': 'User',
    'admin.roleAdmin': 'Admin',
    'admin.sortByDate': 'Sort by Date',
    'admin.user': 'User',
    'admin.role': 'Role',
    'admin.status': 'Status',
    'admin.lastActive': 'Last Active',
    'admin.actions': 'Actions',
    'admin.active': 'Active',
    'admin.inactive': 'Inactive',
    'admin.showing': 'Showing',
    'admin.of': 'of',
    'admin.userCount': 'users',
    'admin.comingSoon': 'Coming soon.',
    'admin.today': 'Today',
    'admin.hoursAgo': '2 hours ago',
    'admin.dayAgo': '1 day ago',
    'admin.daysAgo': '{count} days ago',
    'admin.users.pageTitle': 'Users Management',
    'admin.users.pageSubtitle': 'Monitor your system performance and user activity',
    // Admin Resumes
    'admin.resumes.pageTitle': 'Resumes',
    'admin.resumes.pageSubtitle': 'View and manage all resume submissions',
    'admin.resumeDetails.title': 'Resume Details',
    'admin.resumeDetails.subtitle': 'Review extracted data and AI optimization results',
    'admin.resumeDetails.backToResumes': 'Back to Resumes',
    'admin.resumeInformation.title': 'Resume Information',
    'admin.resumeInformation.id': 'Resume ID',
    'admin.resumeInformation.contentType': 'Content Type',
    'admin.resumeInformation.user': 'User',
    'admin.resumeInformation.originalFilename': 'Original Filename',
    'admin.resumeInformation.created': 'Created',
    'admin.resumeInformation.fileSize': 'File Size',
    'admin.resumeInformation.analyzed': 'Analyzed',
    'admin.resumeInformation.yes': 'Yes',
    'admin.resumeInformation.no': 'No',
    'admin.userInformation.title': 'User Information',
    'admin.userInformation.userId': 'User ID',
    'admin.userInformation.email': 'Email',
    'admin.userInformation.requestNumber': 'Request #',
    'admin.userInformation.status': 'Status',
    'admin.userInformation.active': 'Active',
    'admin.aiOptimization.title': 'AI Optimization Status',
    'admin.aiOptimization.optimized': 'Optimized',
    'admin.aiOptimization.description':
      'AI analysis has been completed. Review the optimization results below.',
    'admin.aiOptimization.dataPreview': 'Data Preview',
    'admin.downloadOptions.title': 'Download Options',
    'admin.downloadOptions.downloadOriginal': 'Download Original',
    'admin.downloadOptions.originalUploaded': 'Original file uploaded by user',
    'admin.downloadOptions.downloadOptimized': 'Download Optimized',
    'admin.downloadOptions.aiEnhanced': 'AI enhanced version',
    'admin.extractedText.title': 'Extracted Text Preview',
    // Admin Dashboard (Resumes Dashboard)
    'admin.dashboard.resumesTitle': 'Resumes Dashboard',
    'admin.dashboard.resumesSubtitle':
      'Manage and track all uploaded resumes and their analysis status',
    'admin.dashboard.exportToExcel': 'Export to Excel',
    'admin.dashboard.filters.status': 'Status',
    'admin.dashboard.filters.sortBy': 'Sort by',
    'admin.dashboard.filters.all': 'All',
    'admin.dashboard.filters.newest': 'Newest',
    'admin.dashboard.filters.oldest': 'Oldest',
    'admin.dashboard.filters.searchPlaceholder': 'Search by name or email',
    'admin.dashboard.showing': 'Showing',
    'admin.dashboard.of': 'of',
    'admin.dashboard.resumesCountLabel': 'resumes',
    'admin.dashboard.columns.requestNumber': 'Request #',
    'admin.dashboard.columns.user': 'User',
    'admin.dashboard.columns.dateTime': 'Date & Time',
    'admin.dashboard.view': 'View',
    'admin.dashboard.status.optimized': 'Optimized',
    'admin.dashboard.status.analyzed': 'Analyzed',
    'admin.dashboard.status.failed': 'Failed',
    'admin.dashboard.pagination.previous': 'Previous',
    'admin.dashboard.pagination.next': 'Next',
    // Claims Management Page
    'claims.title': 'Claims Management',
    'claims.subtitle': 'Review and manage user claims submitted through contact forms',
    'claims.subtitleLine1': 'Review and manage user claims submitted through',
    'claims.subtitleLine2': 'contact forms',
    'claims.overview': 'Claims Overview',
    'claims.openClaims': 'Open Claims',
    'claims.inReview': 'In Review',
    'claims.resolved': 'Resolved',
    'claims.allClaims': 'All Claims',
    'claims.searchPlaceholder': 'Search claims by ID, user, or subject...',
    'claims.filterAllStatus': 'All Status',
    'claims.filterRecentFirst': 'Recent First',
    'claims.export': 'Export',
    'claims.advancedFilter': 'Advanced Filter',
    'claims.claimId': 'Claim ID',
    'claims.user': 'User',
    'claims.subject': 'Subject',
    'claims.status': 'Status',
    'claims.submitted': 'Submitted',
    'claims.actions': 'Actions',
    'claims.statusInReview': 'In Review',
    'claims.statusResolved': 'Resolved',
    'claims.statusOpen': 'Open',
    'claims.showingOf': 'Showing',
    'claims.of': 'of',
    'claims.claims': 'claims',
    // Verify Email Page
    checkYourEmail: 'Check Your Email',
    almostThere: "You're almost there! We sent a confirmation email to:",
    justOneMoreStep: 'Just one more step:',
    step1CheckInbox: 'Open your email inbox (check spam too, just in case)',
    step2ClickLink: 'Click the confirmation link we sent you',
    step3AutoLogin: "That's it! You'll be signed in automatically",
    emailResent: 'Email sent! Check your inbox.',
    resendFailed: "Couldn't send email. Please try again.",
    noEmailYet: "No email yet? It can take a minute.",
    alreadyConfirmed: 'Already confirmed your email?',
    signInHere: 'Sign in here',
    backToSignup: 'Back to Sign Up',
    // Forgot Password Page
    forgotPasswordHero: 'Forgot Your Password?',
    noWorriesHappen: "No worries, it happens! We'll help you get back into your account in no time.",
    resetPasswordTitle: 'Reset Password',
    enterEmailToReset: "Enter your email and we'll send you a link to create a new password.",
    emailRequired: 'Please enter your email address.',
    resetPasswordFailed: "We couldn't send the reset email. Please try again.",
    resetEmailSent: 'Reset link sent! Check your email.',
    checkYourInbox: 'Check Your Inbox',
    resetLinkOnWay: "We've sent you an email with a link to reset your password:",
    hereIsWhatToDo: "Here's what to do:",
    step1OpenEmail: 'Open your email (check spam if needed)',
    step2ClickResetLink: 'Click the reset link in the email',
    step3PickNewPassword: "Pick a new password and you're all set!",
    wrongEmailQuestion: "Wrong email or didn't get it?",
    tryAgain: 'Try Again',
    sendMeResetLink: 'Send Me a Reset Link',
    sendingLink: 'Sending...',
    backToSignIn: 'Back to Sign In',
    dontHaveAccount: "Don't have an account?",
    // Reset Password Page
    pickNewPassword: 'Pick a New Password',
    makeItStrong: 'Make it something secure that you can remember.',
    createYourNewPassword: 'Create Your New Password',
    chooseSecurePassword: 'Choose something secure with at least 6 characters.',
    newPassword: 'New Password',
    enterNewPassword: 'Enter your new password',
    confirmNewPassword: 'Confirm Password',
    reEnterNewPassword: 'Enter it again to confirm',
    samePassword: "That's the same as your old password. Please choose a different one.",
    youreAllSet: "You're All Set!",
    passwordChangedSuccess: "Your password has been changed. You're now signed in and ready to go.",
    continueToHome: 'Continue to Home',
    savingPassword: 'Saving...',
    saveNewPassword: 'Save New Password',
    invalidResetLink: 'This reset link has expired. Please request a new one.',
    passwordStrength: 'Password Strength',
  },
  ar: {
    welcomeBack: 'مرحباً بعودتك',
    loginSubtitle: 'سجل الدخول لمواصلة تحسين مسيرتك المهنية',
    emailAddress: 'البريد الإلكتروني',
    enterEmail: 'أدخل بريدك الإلكتروني',
    password: 'كلمة المرور',
    enterPassword: 'أدخل كلمة مرور قوية',
    rememberMe: 'تذكرني',
    forgotPassword: 'نسيت كلمة المرور؟',
    login: 'تسجيل الدخول',
    orContinueWith: 'أو تواصل مع',
    continueWithGoogle: 'المتابعة باستخدام جوجل',
    orSignUpWith: 'أو سجل باستخدام',
    continueWithGoogleSignUp: 'المتابعة مع جوجل',
    noAccount: 'ليس لديك حساب؟',
    signUp: 'سجل الآن',
    createAccount: 'إنشاء حساب',
    signupSubtitle: 'أنشئ حساباً لمواصلة تحسين مسيرتك المهنية',
    fullName: 'الاسم الكامل',
    enterFullName: 'أحمد محمد',
    networkStrength: 'قوة كلمة المرور',
    confirmPassword: 'تأكيد كلمة المرور',
    reEnterPassword: 'أعد إدخال كلمة المرور',
    agreeToTerms: 'أوافق على شروط الخدمة و سياسة الخصوصية',
    createAccountBtn: 'إنشاء الحساب',
    haveAccount: 'لديك حساب بالفعل؟ تسجيل الدخول',
    signIn: 'تسجيل الدخول',
    signingIn: 'جاري تسجيل الدخول...',
    signInSuccess: 'مرحبًا بعودتك! تم تسجيل الدخول بنجاح.',
    signUpSuccess: 'تم إنشاء الحساب بنجاح! يرجى التحقق من بريدك الإلكتروني.',
    failedToSignIn: 'فشل تسجيل الدخول. يرجى التحقق من بياناتك.',
    signOut: 'تسجيل الخروج',
    signingOut: 'جاري تسجيل الخروج...',
    signOutSuccess: 'تم تسجيل الخروج بنجاح.',
    signOutError: 'فشل تسجيل الخروج. يرجى المحاولة مرة أخرى.',
    signOutConfirmTitle: 'تسجيل الخروج',
    signOutConfirmMessage: 'هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟',
    cancel: 'إلغاء',
    // Auth Success/Error Messages
    accountCreated: 'تم إنشاء الحساب!',
    emailVerified: 'تم التحقق من البريد الإلكتروني بنجاح! أنت الآن مسجل الدخول.',
    emailVerifiedTitle: 'أنت معنا الآن!',
    emailVerifiedMessage: 'تم التحقق من بريدك الإلكتروني. مرحباً بك في ResumeAI!',
    verificationEmailSent: 'لقد أرسلنا رسالة تحقق إلى:',
    checkEmailToVerify: 'يرجى التحقق من بريدك الإلكتروني والنقر على رابط التحقق لتفعيل حسابك.',
    emailResentSuccess: 'تم إعادة إرسال رسالة التحقق!',
    resendEmail: 'إعادة إرسال رسالة التحقق',
    resendIn: 'إعادة الإرسال خلال',
    sending: 'جاري الإرسال...',
    goToSignIn: 'الذهاب لتسجيل الدخول',
    creatingAccount: 'جاري إنشاء الحساب...',
    passwordsDoNotMatch: 'كلمات المرور غير متطابقة.',
    passwordTooShort: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل.',
    mustAgreeToTerms: 'يجب الموافقة على الشروط والأحكام.',
    failedToCreateAccount: 'فشل في إنشاء الحساب. يرجى المحاولة مرة أخرى.',
    accountCreatedSignInFailed: 'تم إنشاء الحساب لكن فشل تسجيل الدخول. يرجى تسجيل الدخول يدوياً.',
    failedToResendEmail: 'فشل في إعادة إرسال البريد. يرجى المحاولة مرة أخرى.',
    failedGoogleSignUp: 'فشل التسجيل بواسطة Google.',
    unexpectedError: 'حدث خطأ غير متوقع. يرجى المحاولة مرة أخرى.',
    verificationFailed: 'فشل التحقق من البريد الإلكتروني. يرجى المحاولة مرة أخرى.',
    authFailed: 'فشل المصادقة. يرجى المحاولة مرة أخرى.',
    // Friendly signin error messages
    wrongPassword: 'كلمة المرور غير صحيحة. حاول مرة أخرى!',
    pleaseVerifyFirst: 'يرجى تأكيد بريدك الإلكتروني أولاً. تحقق من صندوق الوارد!',
    noAccountFound: 'لم نجد حساباً بهذا البريد. لنقم بإنشاء واحد!',
    tooManyTries: 'محاولات كثيرة. خذ استراحة وحاول مرة أخرى.',
    somethingWentWrong: 'حدث خطأ ما. حاول مرة أخرى.',
    oopsSomethingWrong: 'عذراً! حدث خطأ ما. حاول مرة أخرى.',
    invalidCredentials: 'البريد الإلكتروني أو كلمة المرور غير صحيحة.',
    letsGetYouStarted: 'لنبدأ! فقط أكمل البيانات أدناه.',
    signUpRequired: 'التسجيل مطلوب',
    signUpToUpload: 'يرجى إنشاء حساب أو تسجيل الدخول لرفع سيرتك الذاتية واستخدام تحسين CVLab بالذكاء الاصطناعي.',
    signUpNow: 'سجل الآن',
    optimizeCV: 'حسن مسيرتك الذاتية مع سيفي لاب',
    optimizeCareer: 'حسن مسيرتك الذاتية مع سيفي لاب',
    transformResume: 'حول سيرتك الذاتية من خلال التحسين الذكي واحصل على وظيفة أحلامك بشكل أسرع من أي وقت مضى.',
    transformCV: 'حول سيرتك الذاتية من خلال التحسين الذكي واحصل على وظيفة أحلامك بشكل أسرع من أي وقت مضى.',
    weak: 'ضعيف',
    good: 'جيد',
    strong: 'قوي',
    home: 'الرئيسية',
    about: 'من نحن',
    contact: 'تواصل معنا',
    getStarted: 'ابدأ الآن',
    heroTitle: 'سيرتك الذاتية، محسنة مع سيفي لاب',
    heroSubtitle: 'ارفع سيرتك الذاتية ودع الذكاء الاصطناعي يحللها ويحسنها ويهيئها لأفضل فرص العمل في ثوان معدودة',
    dropResume: 'اسحب سيرتك الذاتية هنا',
    supportedFormats: 'يدعم PDF, DOCX . حتى 10 ميجابايت',
    uploadResume: 'رفع السيرة الذاتية',
    howItWorks: 'كيف يعمل الموقع؟',
    stepSubtitle: 'ثلاث خطوات بسيطة للحصول على سيرة ذاتية مثالية',
    step1Title: 'ارفع سيرتك الذاتية',
    step1Desc: 'ببساطة اسحب وأفلت سيرتك الذاتية أو انقر للرفع. ندعم صيغ PDF و Word',
    step2Title: 'نحلل سيرتك الذاتية ونسألك عنها',
    step2Desc: 'نحلل السيرة الذاتية بالتفصيل، نحصر المناطق اللي تحتاج تحسين فيها، ثم نسألك عنها',
    step3Title: 'نعيد كتابة سيرتك الذاتية بعد التحسين',
    step3Desc: 'ونوفرها لك بـ 3 نماذج، كل نموذج بصيغة Word و PDF',
    resumeAI: 'ResumeAI',
    perfectingResumes: 'تحسين السيرة الذاتية مع سيفي لاب',
    quickLinks: 'روابط سريعة',
    legal: 'قانوني',
    privacyPolicy: 'سياسة الخصوصية',
    termsOfService: 'شروط الخدمة',
    // Terms of Service Page
    termsTitle: 'الشروط والأحكام',
    termsSubtitle: 'CVLab سيفي لاب',
    termsLastUpdated: 'آخر تحديث: يناير ٢٠٢٦',
    termsSection1Title: '١. مقدمة',
    termsSection1Text: 'مرحباً بكم في سيفي لاب ("نحن" أو "لنا"). باستخدامكم لموقعنا وخدماتنا، فإنكم توافقون على الالتزام بهذه الشروط والأحكام. يرجى قراءتها بعناية قبل استخدام منصتنا لإنشاء السير الذاتية.',
    termsSection2Title: '٢. التعريفات',
    termsSection2Text: '"الخدمة" تشير إلى أدوات إنشاء السيرة الذاتية والقوالب والميزات ذات الصلة التي يوفرها سيفي لاب.\n\n"المستخدم" يشير إلى أي فرد يصل إلى خدمتنا أو يستخدمها.\n\n"المحتوى" يشير إلى أي نصوص أو صور أو بيانات أو مواد يتم رفعها أو إنشاؤها عبر خدمتنا.',
    termsSection3Title: '٣. تسجيل الحساب',
    termsSection3Text: 'للوصول إلى بعض الميزات، قد تحتاج إلى إنشاء حساب. توافق على تقديم معلومات دقيقة وكاملة عند التسجيل والحفاظ على أمان بيانات حسابك. أنت مسؤول عن جميع الأنشطة التي تتم تحت حسابك.',
    termsSection4Title: '٤. وصف الخدمات',
    termsSection4Text: 'يوفر سيفي لاب أدوات عبر الإنترنت لإنشاء وتحرير وتحميل السير الذاتية الاحترافية. نقدم قوالب متنوعة وخيارات تنسيق وإمكانيات تصدير. قد تختلف الميزات بناءً على خطط الاشتراك.',
    termsSection5Title: '٥. مسؤوليات المستخدم',
    termsSection5Text: 'توافق على استخدام خدمتنا لأغراض مشروعة فقط ووفقاً لهذه الشروط. لا يجوز لك استخدام الخدمة لإنشاء مستندات كاذبة أو مضللة أو احتيالية. أنت وحدك المسؤول عن دقة المعلومات المدرجة في سيرتك الذاتية.',
    termsSection6Title: '٦. الملكية الفكرية',
    termsSection6Text: 'جميع القوالب والتصاميم والبرامج والمواد الأخرى التي يوفرها سيفي لاب محمية بحقوق الملكية الفكرية. يمكنك استخدام هذه المواد للأغراض الشخصية غير التجارية فقط. تحتفظ بملكية المحتوى والبيانات الشخصية الخاصة بك.',
    termsSection7Title: '٧. المشتريات والدفع',
    termsSection7Text: 'قد تتطلب بعض الميزات الدفع. يتم عرض جميع الأسعار بالعملة المطبقة وتشمل أي ضرائب سارية ما لم يُذكر خلاف ذلك. يجب إتمام الدفع من خلال طرق الدفع المعتمدة لدينا. بإجراء عملية شراء، فإنك تأذن لنا بخصم المبلغ من وسيلة الدفع المختارة.',
    termsSection8Title: '٨. سياسة الاسترداد والإرجاع',
    termsSection8Text: 'نظراً للطبيعة الرقمية لخدماتنا، لا تتوفر عمليات استرداد الأموال بشكل عام بمجرد الوصول إلى الخدمة أو تحميلها. ومع ذلك، قد ننظر في طلبات الاسترداد على أساس كل حالة على حدة خلال ١٤ يوماً من الشراء إذا لم يتم تقديم الخدمة كما هو موصوف أو منعت مشاكل تقنية الوصول إليها. لطلب استرداد، يرجى التواصل مع فريق الدعم مع تفاصيل طلبك.',
    termsSection9Title: '٩. الخصوصية',
    termsSection9Text: 'يخضع استخدامك لخدمتنا أيضاً لسياسة الخصوصية الخاصة بنا. نجمع ونعالج البيانات الشخصية كما هو موضح فيها. باستخدام خدمتنا، فإنك توافق على هذه المعالجة.',
    termsSection10Title: '١٠. حدود المسؤولية',
    termsSection10Text: 'إلى أقصى حد يسمح به القانون، لن يكون سيفي لاب مسؤولاً عن أي أضرار غير مباشرة أو عرضية أو خاصة أو تبعية أو عقابية ناتجة عن استخدامك للخدمة. لن تتجاوز مسؤوليتنا الإجمالية المبلغ الذي دفعته مقابل الخدمة.',
    termsSection11Title: '١١. التغييرات على الشروط',
    termsSection11Text: 'نحتفظ بالحق في تعديل هذه الشروط في أي وقت. ستصبح التغييرات سارية عند نشرها. استمرارك في استخدام الخدمة بعد التغييرات يعني قبولك للشروط المعدلة.',
    termsSection12Title: '١٢. القانون الذي يتبع له الموقع',
    termsSection12Text: 'تخضع هذه الشروط وتُفسر وفقاً للقوانين المعمول بها في المملكة العربي السعودية التي يعمل فيها سيفي لاب.',
    termsSection13Title: '١٣. تواصل معنا',
    termsSection13Text: 'إذا كانت لديك أي أسئلة حول هذه الشروط، يرجى التواصل معنا عبر موقعنا الإلكتروني.',
    copyright: '© 2026 CVLab. جميع الحقوق محفوظة',
    // About Us Page
    aboutUsTitle: 'من نحن',
    aboutUsSubtitle: 'CVLab سيفي لاب',
    aboutUsWhoWeAreTitle: 'من نحن',
    aboutUsWhoWeAreText: 'سيفي لاب هي منصة ذكية لتحسين السير الذاتية، صُممت لمساعدتك في إنشاء سيرة ذاتية احترافية ومتقنة تعكس مهاراتك وخبراتك بشكل حقيقي.',
    aboutUsHowItWorksTitle: 'كيف نعمل',
    aboutUsHowItWorksSubtitle: 'تستخدم منصتنا أسلوباً بسيطاً وفعالاً:',
    aboutUsStep1Title: 'ارفع سيرتك الذاتية',
    aboutUsStep1Desc: 'قدّم سيرتك الذاتية الحالية إلى منصتنا.',
    aboutUsStep2Title: 'مراجعة ذكية',
    aboutUsStep2Desc: 'نحلل سيرتك الذاتية ونحدد النقاط التي تحتاج توضيحاً أو تحسيناً.',
    aboutUsStep3Title: 'أسئلة تفاعلية',
    aboutUsStep3Desc: 'نطرح عليك أسئلة محددة حول الأقسام غير الواضحة أو الناقصة.',
    aboutUsStep4Title: 'إعادة كتابة احترافية',
    aboutUsStep4Desc: 'بناءً على إجاباتك، نعيد كتابة سيرتك الذاتية لتصبح وثيقة احترافية متقنة.',
    aboutUsMissionTitle: 'رسالتنا',
    aboutUsMissionText: 'نؤمن بأن الجميع يستحق سيرة ذاتية تفتح له الأبواب. هدفنا هو سد الفجوة بين إمكانياتك وطريقة تقديمها، لنساعدك على التميز أمام أصحاب العمل.',
    // Processing Page
    processingTitle: 'جاري العمل على تحسين سيرتك الذاتية ....',
    processingDescription: 'جاري العمل على تحليل سيرتك الذاتية لايجاد مناطق التحسين الممكنة فيها ..',
    processingStatusLabel: 'جار التحسين بالذكاء الاصطناعي',
    processingLabel: 'معالجة',
    proTipTitle: 'Pro Tip',
    proTipText: 'يمكن للسير الذاتية المحسنة زيادة فرص مقابلة التوظيف بنسبة تصل إلى 70%.',
    // Payment Page
    paymentTitle: 'أكمل عملية الدفع',
    paymentDescription: 'سيرتك الذاتية جاهزة للتحسين بالذكاء الاصطناعي. أكمل الدفع للحصول على تحليل وتحسينات احترافية.',
    secureCheckout: 'دفع آمن',
    orderSummary: 'ملخص الطلب',
    aiWillOptimize: 'سيقوم الذكاء الاصطناعي بتحسين:',
    atsOptimization: 'تحسين ATS',
    grammarClarity: 'تصحيح النحو والوضوح',
    keywordEnhancement: 'تحسين الكلمات المفتاحية',
    professionalFormatting: 'تنسيق احترافي',
    resumeOptimization: 'تحسين السيرة الذاتية',
    total: 'الإجمالي',
    paymentDetails: 'تفاصيل الدفع',
    limitedOffer: 'عرض محدود: خصم 50%',
    contactInformation: 'معلومات التواصل',
    emailAddressLabel: 'عنوان البريد الإلكتروني',
    paymentMethod: 'طريقة الدفع',
    card: 'بطاقة',
    cardNumber: 'رقم البطاقة',
    expiryDate: 'تاريخ الانتهاء',
    cvc: 'CVC',
    saveCard: 'حفظ البطاقة لشراء مستقبلي',
    payOptimize: 'دفع وتحسين سيرتي الذاتية',
    securePayment: 'دفع آمن مدعوم بـ Stripe',
    noRecurring: 'لا توجد رسوم متكررة - دفع مرة واحدة فقط',
    readyForOptimization: 'سيرتك الذاتية جاهزة للتحسين بالذكاء الاصطناعي. أكمل الدفع للمتابعة واحصل على سيرتك الذاتية المحسنة احترافيا في دقائق.',
    // Profile Page
    profile: 'الملف الشخصي',
    'profile.title': 'الملف الشخصي',
    'profile.subtitle': 'إدارة معلومات حسابك الشخصي',
    'profile.changePhoto': 'تغيير الصورة',
    'profile.firstName': 'الاسم الأول',
    'profile.lastName': 'اسم العائلة',
    'profile.email': 'البريد الإلكتروني',
    'profile.changePassword': 'تغيير كلمة المرور',
    'profile.currentPassword': 'كلمة المرور الحالية',
    'profile.newPassword': 'كلمة المرور الجديدة',
    'profile.confirmPassword': 'تأكيد كلمة المرور الجديدة',
    'profile.saveChanges': 'حفظ التغييرات',
    'profile.cancel': 'إلغاء',
    'profile.accountActions': 'إجراءات الحساب',
    'profile.downloadData': 'تنزيل البيانات',
    'profile.logout': 'تسجيل الخروج',
    'profile.deleteAccount': 'حذف الحساب',
    'profile.accountInfo': 'معلومات الحساب',
    'profile.memberSince': 'انضم في',
    'profile.lastSignIn': 'آخر تسجيل دخول',
    'profile.january2023': 'يناير 2023',
    'profile.twoDaysAgo': 'قبل يومين',
    'profile.lastUpdated': 'آخر تحديث',
    'profile.activityHistory': 'سجل النشاطات',
    'profile.noActivity': 'لا يوجد نشاط',
    'profile.uploadResumeToSeeActivity': 'قم برفع سيرتك الذاتية لرؤية سجل النشاطات',
    'profile.resumeDownloaded': 'تحميل السيرة الذاتية',
    'profile.downloadedOptimized': 'تم تحميل النسخة المحسنة بصيغة PDF',
    'profile.daysAgo': 'منذ أيام',
    'profile.twoDaysAgoActivity': 'منذ يومين',
    // Contact Page
    'contact.title': 'اتصل بنا',
    'contact.subtitle': 'نحن هنا لمساعدتك. تواصل معنا في أي وقت',
    'contact.contactInfo': 'معلومات التواصل',
    'contact.email': 'البريد الإلكتروني',
    'contact.address': 'العنوان',
    'contact.riyadh': 'الرياض',
    'contact.saudiArabia': 'المملكة العربية السعودية',
    'contact.addressFull': 'الرياض, المملكة العربية السعودية',
    'contact.faq': 'الأسئلة الشائعة',
    'contact.faq1': 'كيف يعمل تحسين السيرة الذاتية؟',
    'contact.faq2': 'هل بياناتي آمنة ومحمية؟',
    'contact.faq3': 'كم من الوقت يستغرق التحسين ؟',
    'contact.sendMessage': 'أرسل لنا رسالة',
    'contact.replyTime': 'نرد عادة خلال 24 ساعة',
    'contact.fullName': 'الاسم الكامل',
    'contact.fullNamePlaceholder': 'أدخل اسمك الكامل',
    'contact.emailPlaceholder': 'your@email.com',
    'contact.phoneNumber': 'رقم الهاتف',
    'contact.phonePlaceholder': '0555555555',
    'contact.message': 'الرسالة',
    'contact.messagePlaceholder': 'اكتب رسالتك هنا...',
    'contact.sendBtn': 'إرسال الرسالة',
    'contact.confidential': 'معلوماتك سرية وآمنة تماماً',
    'contact.needHelp': 'تحتاج مساعدة فورية؟',
    'contact.supportText': 'فريق الدعم متاح للمساعدة في أي وقت. نحن نقدر وقتك ونسعى لحل استفساراتك بأسرع وقت ممكن',
    'contact.liveChat': 'دردشة مباشرة',
    'contact.helpCenter': 'مركز المساعدة',
    // Questions Page
    questions: 'أسئلة',
    ready: 'جاهز',
    pages: 'صفحات',
    resumeOptimizationTitle: 'أسئلة تحسين السيرة الذاتية',
    resumeOptimizationSubtitle: 'أجب على الأسئلة التالية لمساعدتنا في تخصيص تحليل سيرتك الذاتية وتقديم التوصيات الأكثر صلة',
    progress: 'التقدم',
    question1Title: 'ما هو المسمى الوظيفي المستهدف؟',
    question1Subtitle: 'يساعدنا هذا في تخصيص التوصيات لأهدافك المهنية المحددة',
    question1Placeholder: 'مثال: مهندس برمجيات أول، مدير تسويق',
    question2Title: 'ما هو المجال المستهدف؟',
    question2Subtitle: 'المجالات المختلفة لها تفضيلات مختلفة للكلمات الرئيسية',
    question2Placeholder: 'مثال: مهندس برمجيات أول، مدير تسويق',
    question3Title: 'سنوات الخبرة؟',
    question3Subtitle: 'يساعدنا هذا في معايرة التحليل لمستواك المهني',
    question3Placeholder: 'مثال 4 سنوات',
    question4Title: 'ما هي مهاراتك الرئيسية؟',
    question4Subtitle: 'أدخل 5 - 10 مهاراتك الأكثر صلة بمنصبك المستهدف',
    question4Placeholder: 'مثال بايثون، إدارة المشاريع، تحليل البيانات، قيادة ريتاكي.....',
    question5Title: 'هل لديك وظيفة محددة في الاعتبار ؟',
    question5Subtitle: 'اختياري: الصق رابط وصف الوظيفة أو المتطلبات الأساسية لتحسينها للوظيفة المحددة',
    question5Placeholder: 'صق رابط وصف الوظيفة أو المتطلبات الأساسية هنا (اختياري)',
    analyzeButton: 'تحليل وتحسين السيرة الذاتية',
    // Resume Preview Page
    'templateSelector.title': 'اختر قالب السيرة الذاتية',
    'templateSelector.classic.name': 'كلاسيكي',
    'templateSelector.classic.description': 'تقليدي واحترافي',
    'templateSelector.classic.tag1': 'متوافق مع ATS',
    'templateSelector.classic.tag2': 'تصميم نظيف',
    'templateSelector.modern.name': 'عصري',
    'templateSelector.modern.description': 'معاصر وإبداعي',
    'templateSelector.modern.tag1': 'تصميم جريء',
    'templateSelector.modern.tag2': 'لافت للنظر',
    'templateSelector.executive.name': 'تنفيذي',
    'templateSelector.executive.description': 'للمناصب القيادية',
    'templateSelector.executive.tag1': 'راقي',
    'templateSelector.executive.tag2': 'أنيق',
    'templateSelector.technical.name': 'تقني',
    'templateSelector.technical.description': 'لمناصب التكنولوجيا',
    'templateSelector.technical.tag1': 'تركيز المهارات',
    'templateSelector.technical.tag2': 'مكتبة التقنيات',
    'optimization.title': 'نصائح التحسين',
    'optimization.atsOptimized': 'تم تحسين السيرة الذاتية لتناسب أنظمة ATS',
    'optimization.keywordsEnhanced': 'تم تحسين الكلمات المفتاحية بنسبة 35%',
    'optimization.formattingImproved': 'تم تحسين التنسيق لتحسين القراءة',
    'resumePreview.title': 'عرض السيرة الذاتية',
    'resumePreview.download': 'تحميل السيفي PDF و Word',
    'resume.professionalSummary': 'الملخص المهني',
    'resume.workExperience': 'الخبرة العملية',
    'resume.education': 'التعليم',
    'resume.technicalSkills': 'المهارات التقنية',
    'resume.certifications': 'الشهادات',
    'resume.present': 'Present',
    'resume.name': 'Abdullah Alshehri',
    'resume.title': 'Senior Software Engineer',
    'resume.email': 'abdullah@email.com',
    'resume.phone': '+966 50 123 4567',
    'resume.location': 'Riyadh, Saudi Arabia',
    'resume.professionalSummaryText': 'Results-driven Senior Software Engineer with 8+ years of experience in full-stack development, cloud architecture, and team leadership. Proven track record of delivering scalable solutions that improve system performance by 40% and reduce operational costs by $200K annually.',
    'resume.workExp1.title': 'Senior Software Engineer',
    'resume.workExp1.company': 'Tech Solutions Inc.',
    'resume.workExp1.period': '2020 - Present',
    'resume.workExp1.bullet1': 'Led a team of 6 engineers to develop microservices architecture, improving system scalability by 60%',
    'resume.workExp1.bullet2': 'Implemented CI/CD pipelines reducing deployment time from 4 hours to 15 minutes',
    'resume.workExp1.bullet3': 'Optimized database queries resulting in 45% faster response times',
    'resume.workExp2.title': 'Software Engineer',
    'resume.workExp2.company': 'Digital Innovations LLC',
    'resume.workExp2.period': '2017 - 2020',
    'resume.workExp2.bullet1': 'Developed RESTful APIs serving 1M+ daily requests with 99.9% uptime',
    'resume.workExp2.bullet2': 'Collaborated with cross-functional teams to deliver 15+ projects on time',
    'resume.education.degree': 'Bachelor of Computer Science',
    'resume.education.university': 'King Saud University',
    'resume.education.period': '2013 - 2017',
    'resume.skills.languages': 'Languages',
    'resume.skills.languagesList': 'Python, JavaScript, Java, Go',
    'resume.skills.frameworks': 'Frameworks',
    'resume.skills.frameworksList': 'React, Node.js, Django',
    'resume.skills.cloud': 'Cloud',
    'resume.skills.cloudList': 'AWS, Azure, Docker, Kubernetes',
    'resume.skills.databases': 'Databases',
    'resume.skills.databasesList': 'PostgreSQL, MongoDB, Redis',
    'resume.cert1': 'AWS Certified Solutions Architect',
    'resume.cert2': 'Certified Kubernetes Administrator',
    'resume.cert3': 'Professional Scrum Master I',
    // Prompt Management Page (/prompt-management)
    'pm.brand': 'مركز الإدارة',
    'pm.nav.admin': 'الإدارة',
    'pm.nav.dashboard': 'لوحة التحكم',
    'pm.user.adminUser': 'مستخدم مسؤول',
    'pm.user.email': 'admin@company.com',
    'pm.page.title': 'إدارة البرومبتس',
    'pm.page.subtitle':
      'تكوين نماذج الذكاء الاصطناعي وإدارة قوالب تحليل السيرة الذاتية',
    'pm.llm.title': 'تكوين نموذج الذكاء الاصطناعي',
    'pm.llm.provider': 'مزود الخدمة',
    'pm.llm.model': 'النموذج',
    'pm.llm.saveButton': 'حفظ إعدادات النموذج',
    'pm.prompt.analyzeResume.title': 'تحليل السيرة الذاتية',
    'pm.prompt.analyzeResume.subtitle': 'بروميت لتحليل السيرة الذاتية الشامل',
    'pm.prompt.analyzeResume.description':
      'قم بإجراء تحليل شامل للسيرة الذاتية المقدمة. قيّم الجوانب التالية: 1. جودة الهيكل والتنسيق الإجمالية 2. صلة المحتوى واكتماله 3. محاذاة المهارات مع معايير الصناعة 4. عرض الخبرة والتحديد الكمي 5. توافقية ATS وتحسين الكلمات الرئيسية قدم درجة مفصلة (1-10) لكل فئة مع الشروحات والتوصيات التحسينية.',
    'pm.prompt.analyzeResume.lastUpdated': 'منذ 5 ساعات',
    'pm.prompt.questionGeneration.title': 'سؤال توليد السيرة الذاتية',
    'pm.prompt.questionGeneration.subtitle':
      'بروميت لإنشاء أسئلة مقابلة بناء على السيرة الذاتية',
    'pm.prompt.questionGeneration.description':
      'بناءً على السيرة الذاتية المقدمة، قم بإنشاء أسئلة ذات صلة ستساعد في تقييم مؤهلات المرشح. قم بإنشاء أسئلة في الفئات التالية: 1. المهارات التقنية والخبرة 2. أسئلة سلوكية تستند إلى الخبرة 3. استفسارات الإنجازات والإنجازات 4. أسئلة سيناريو حل المشاكل 5. أسئلة التوافق الثقافي والدافع قدم 3-5 أسئلة لكل فئة بمستويات صعوبة متفاوتة.',
    'pm.prompt.questionGeneration.lastUpdated': 'منذ يوم واحد',
    'pm.prompt.optimizeResume.title': 'بروميت تحسين السيرة الذاتية',
    'pm.prompt.optimizeResume.subtitle': 'قالب لاقتراحات تحسين السيرة الذاتية',
    'pm.prompt.optimizeResume.description':
      'أنت خبير في تحسين السيرة الذاتية. قم بتحليل السيرة الذاتية المقدمة واقترح تحسينات محددة لتحسين فعاليتها لطلبات الوظائف. ركز على: 1. تحسين المحتوى وتحسين الكلمات الرئيسية 2. تحسينات التنسيق والهيكل 3. إبراز المهارات والتحديد الكمي 4. توصيات اللغة القائمة على الإنجازات قدم ملاحظات قابلة للتنفيذ مع أمثلة محددة.',
    'pm.prompt.optimizeResume.lastUpdated': 'منذ ساعتين',
    'pm.buttons.preview': 'معاينة',
    'pm.buttons.edit': 'تعديل',
    'pm.buttons.saveChanges': 'حفظ التغييرات',
    'pm.lastUpdated': 'آخر تحديث:',
    'pm.status.active': 'نشط',
    'pm.status.draft': 'مسود',
    // Admin (cv-build /admin/*)
    'admin.adminHub': 'لوحة الإدارة',
    'admin.admin': 'المسؤول',
    'admin.overview': 'نظرة عامة',
    'admin.dashboardOverview': 'نظرة عامة على لوحة التحكم',
    'admin.monitorPerformance': 'راقب أداء النظام ونشاط المستخدمين',
    'admin.dashboard': 'لوحة التحكم',
    'admin.prompts': 'المطالب',
    'admin.resumes': 'السير الذاتية',
    'admin.users': 'المستخدمون',
    'admin.claims': 'الطلبات',
    'admin.settings': 'الإعدادات',
    'admin.totalUsers': 'إجمالي المستخدمين',
    'admin.totalSessions': 'الجلسات النشطة',
    'admin.resumesProcessed': 'السير الذاتية المعالجة',
    'admin.serverUptime': 'وقت تشغيل الخادم',
    'admin.userManagement': 'إدارة المستخدمين',
    'admin.searchUsers': 'البحث عن المستخدمين....',
    'admin.allStatus': 'جميع الحالات',
    'admin.allRoles': 'جميع الأدوار',
    'admin.roleUser': 'مستخدم',
    'admin.roleAdmin': 'مسؤول',
    'admin.roleManager': 'مدير',
    'admin.sortByDate': 'ترتيب حسب التاريخ',
    'admin.user': 'المستخدم',
    'admin.role': 'الدور',
    'admin.status': 'الحالة',
    'admin.lastActive': 'آخر نشاط',
    'admin.actions': 'الإجراءات',
    'admin.active': 'نشط',
    'admin.inactive': 'غير نشط',
    'admin.showing': 'إظهار',
    'admin.of': 'من',
    'admin.userCount': 'مستخدم',
    'admin.today': 'اليوم',
    'admin.hoursAgo': 'قبل ساعتين',
    'admin.dayAgo': 'قبل يوم واحد',
    'admin.daysAgo': 'قبل {count} أيام',
    'admin.comingSoon': 'قريباً.',
    'admin.users.pageTitle': 'ادارة المستخدمين',
    'admin.users.pageSubtitle': 'راقب أداء النظام ونشاط المستخدمين',
    // Admin Resumes
    'admin.resumes.pageTitle': 'السير الذاتية',
    'admin.resumes.pageSubtitle': 'عرض وإدارة جميع طلبات السير الذاتية',
    'admin.resumeDetails.title': 'تفاصيل السيرة الذاتية',
    'admin.resumeDetails.subtitle': 'معلومات تفصيلية ونتائج التحسين بالذكاء الاصطناعي',
    'admin.resumeDetails.backToResumes': 'العودة للسير الذاتية',
    'admin.resumeInformation.title': 'معلومات السيرة الذاتية',
    'admin.resumeInformation.id': 'المعرف',
    'admin.resumeInformation.contentType': 'نوع المحتوى',
    'admin.resumeInformation.user': 'المستخدم',
    'admin.resumeInformation.originalFilename': 'اسم الملف الأصلي',
    'admin.resumeInformation.created': 'تاريخ الإنشاء',
    'admin.resumeInformation.fileSize': 'حجم الملف',
    'admin.resumeInformation.analyzed': 'تم التحليل',
    'admin.resumeInformation.yes': 'نعم',
    'admin.resumeInformation.no': 'لا',
    'admin.userInformation.title': 'معلومات المستخدم',
    'admin.userInformation.userId': 'معرف المستخدم',
    'admin.userInformation.email': 'البريد الإلكتروني',
    'admin.userInformation.requestNumber': 'رقم الطلب',
    'admin.userInformation.status': 'الحالة',
    'admin.userInformation.active': 'نشط',
    'admin.aiOptimization.title': 'حالة تحسين الذكاء الاصطناعي',
    'admin.aiOptimization.optimized': 'محسن',
    'admin.aiOptimization.description':
      'تم الانتهاء من تحليل الذكاء الاصطناعي. راجع نتائج التحسين أدناه.',
    'admin.aiOptimization.dataPreview': 'معاينة البيانات',
    'admin.downloadOptions.title': 'خيارات التحميل',
    'admin.downloadOptions.downloadOriginal': 'تحميل الأصلي',
    'admin.downloadOptions.originalUploaded': 'الملف المرفع الأصلي',
    'admin.downloadOptions.downloadOptimized': 'تحميل نسخة محسنة PDF و Word',
    'admin.downloadOptions.aiEnhanced': 'نسخة محسنة بالذكاء الاصطناعي',
    'admin.extractedText.title': 'عرض النص المستخرج',
    // Admin Dashboard (Resumes Dashboard)
    'admin.dashboard.resumesTitle': 'لوحة السير الذاتية',
    'admin.dashboard.resumesSubtitle':
      'إدارة وتتبع جميع السير الذاتية المرفوعة وحالة تحليلها',
    'admin.dashboard.exportToExcel': 'تصدير إلى إكسل',
    'admin.dashboard.filters.status': 'الحالة',
    'admin.dashboard.filters.sortBy': 'ترتيب حسب',
    'admin.dashboard.filters.all': 'الكل',
    'admin.dashboard.filters.newest': 'الأحدث',
    'admin.dashboard.filters.oldest': 'الأقدم',
    'admin.dashboard.filters.searchPlaceholder': 'البحث بالاسم أو البريد',
    'admin.dashboard.showing': 'عرض',
    'admin.dashboard.of': 'من',
    'admin.dashboard.resumesCountLabel': 'سيرة ذاتية',
    'admin.dashboard.columns.requestNumber': 'رقم الطلب',
    'admin.dashboard.columns.user': 'المستخدم',
    'admin.dashboard.columns.dateTime': 'التاريخ والوقت',
    'admin.dashboard.view': 'عرض',
    'admin.dashboard.status.optimized': 'محَسَّن',
    'admin.dashboard.status.analyzed': 'محلَّل',
    'admin.dashboard.status.failed': 'فشل',
    'admin.dashboard.pagination.previous': 'السابق',
    'admin.dashboard.pagination.next': 'التالي',
    // Claims Management Page
    'claims.title': 'إدارة الشكاوى',
    'claims.subtitle': 'مراجعة وإدارة شكاوى المستخدمين المقدمة عبر نماذج الاتصال',
    'claims.subtitleLine1': 'مراجعة وإدارة شكاوى المستخدمين المقدمة عبر',
    'claims.subtitleLine2': 'نماذج الاتصال',
    'claims.overview': 'نظرة عامة على الشكاوى',
    'claims.openClaims': 'شكاوى مفتوحة',
    'claims.inReview': 'قيد المراجعة',
    'claims.resolved': 'تم الحل',
    'claims.allClaims': 'جميع الشكاوى',
    'claims.searchPlaceholder': 'البحث عن شكوى بالرقم أو المستخدم أو الموضوع...',
    'claims.filterAllStatus': 'جميع الحالات',
    'claims.filterRecentFirst': 'الحديثة أولا',
    'claims.export': 'تصدير',
    'claims.advancedFilter': 'فلتر متقدم',
    'claims.claimId': 'رقم الشكوى',
    'claims.user': 'المستخدم',
    'claims.subject': 'الموضوع',
    'claims.status': 'الحالة',
    'claims.submitted': 'تم تقديمها',
    'claims.actions': 'الإجراءات',
    'claims.statusInReview': 'قيد المراجعة',
    'claims.statusResolved': 'تم الحل',
    'claims.statusOpen': 'مفتوحة',
    'claims.showingOf': 'إظهار',
    'claims.of': 'من',
    'claims.claims': 'شكوى',
    // Verify Email Page
    checkYourEmail: 'تحقق من بريدك الإلكتروني',
    almostThere: 'أوشكت على الانتهاء! أرسلنا لك رسالة تأكيد إلى:',
    justOneMoreStep: 'خطوة واحدة فقط:',
    step1CheckInbox: 'افتح بريدك الإلكتروني (تحقق من البريد المزعج أيضاً)',
    step2ClickLink: 'اضغط على رابط التأكيد الذي أرسلناه',
    step3AutoLogin: 'هذا كل شيء! سيتم تسجيل دخولك تلقائياً',
    emailResent: 'تم الإرسال! تحقق من بريدك.',
    resendFailed: 'تعذر الإرسال. حاول مرة أخرى.',
    noEmailYet: 'لم يصلك البريد؟ قد يستغرق دقيقة.',
    alreadyConfirmed: 'هل أكدت بريدك الإلكتروني؟',
    signInHere: 'سجل دخولك هنا',
    backToSignup: 'العودة للتسجيل',
    // Forgot Password Page
    forgotPasswordHero: 'نسيت كلمة المرور؟',
    noWorriesHappen: 'لا تقلق، هذا يحدث! سنساعدك للعودة إلى حسابك بسرعة.',
    resetPasswordTitle: 'إعادة تعيين كلمة المرور',
    enterEmailToReset: 'أدخل بريدك الإلكتروني وسنرسل لك رابطاً لإنشاء كلمة مرور جديدة.',
    emailRequired: 'يرجى إدخال بريدك الإلكتروني.',
    resetPasswordFailed: 'تعذر إرسال رابط إعادة التعيين. حاول مرة أخرى.',
    resetEmailSent: 'تم إرسال الرابط! تحقق من بريدك.',
    checkYourInbox: 'تحقق من بريدك',
    resetLinkOnWay: 'أرسلنا لك رابطاً لإعادة تعيين كلمة المرور:',
    hereIsWhatToDo: 'إليك ما يجب فعله:',
    step1OpenEmail: 'افتح بريدك الإلكتروني (تحقق من البريد المزعج)',
    step2ClickResetLink: 'اضغط على رابط إعادة التعيين',
    step3PickNewPassword: 'اختر كلمة مرور جديدة وانتهى الأمر!',
    wrongEmailQuestion: 'بريد خاطئ أو لم يصلك؟',
    tryAgain: 'حاول مرة أخرى',
    sendMeResetLink: 'أرسل لي رابط إعادة التعيين',
    sendingLink: 'جاري الإرسال...',
    backToSignIn: 'العودة لتسجيل الدخول',
    dontHaveAccount: 'ليس لديك حساب؟',
    // Reset Password Page
    pickNewPassword: 'اختر كلمة مرور جديدة',
    makeItStrong: 'اجعلها آمنة وسهلة التذكر.',
    createYourNewPassword: 'أنشئ كلمة مرورك الجديدة',
    chooseSecurePassword: 'اختر كلمة مرور آمنة من 6 أحرف على الأقل.',
    newPassword: 'كلمة المرور الجديدة',
    enterNewPassword: 'أدخل كلمة مرورك الجديدة',
    confirmNewPassword: 'تأكيد كلمة المرور',
    reEnterNewPassword: 'أدخلها مرة أخرى للتأكيد',
    samePassword: 'هذه نفس كلمة المرور القديمة. اختر كلمة مرور مختلفة.',
    youreAllSet: 'تم بنجاح!',
    passwordChangedSuccess: 'تم تغيير كلمة مرورك. أنت الآن مسجل الدخول وجاهز للبدء.',
    continueToHome: 'المتابعة للرئيسية',
    savingPassword: 'جاري الحفظ...',
    saveNewPassword: 'حفظ كلمة المرور الجديدة',
    invalidResetLink: 'انتهت صلاحية هذا الرابط. يرجى طلب رابط جديد.',
    passwordStrength: 'قوة كلمة المرور',
  },
};

// Explicit reference to prevent Next.js from tree-shaking these keys
// This ensures profile.noActivity and profile.uploadResumeToSeeActivity
// are included in the compiled bundle
// We export and use this to prevent optimization
export const _preventTreeShaking = {
  key1: translations.en['profile.noActivity'],
  key2: translations.en['profile.uploadResumeToSeeActivity'],
  key3: translations.ar['profile.noActivity'],
  key4: translations.ar['profile.uploadResumeToSeeActivity'],
};

// Force reference in a way that can't be optimized
if (typeof window !== 'undefined') {
  (window as any).__cvlab_translations = _preventTreeShaking;
}

const LanguageContext = createContext<LanguageContextType | undefined>(
  undefined
);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({
  children,
}) => {
  const [language, setLanguage] = useState<Language>('en');

  useEffect(() => {
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
    document.documentElement.lang = language;
  }, [language]);

  const t = (key: string): string => {
    const translationObj = translations[language];
    if (!translationObj) {
      return '';
    }
    
    // CRITICAL: Use multiple methods to prevent Next.js optimization
    // Method 1: Store hasOwnProperty in a variable to prevent inlining
    const hasOwnProp = Object.prototype.hasOwnProperty;
    const hasKey = hasOwnProp.call(translationObj, key);
    
    // Method 2: Use strict boolean comparison that can't be optimized
    if (hasKey !== true) {
      // Force reference to preventTreeShaking to ensure keys are in bundle
      if (_preventTreeShaking.key1 || _preventTreeShaking.key2) {
        // This code path ensures the keys are referenced
      }
      return '';
    }
    
    // Method 3: Access value with explicit type checking
    const value = (translationObj as Record<string, string>)[key];
    
    // Method 4: Multiple explicit type guards
    if (value === undefined || value === null) {
      return '';
    }
    
    // Method 5: Type check that prevents optimization
    const isString = typeof value === 'string';
    if (!isString) {
      return '';
    }
    
    return value;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
